<a href="https://colab.research.google.com/github/nishanN321/nishanN321/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Machine learning roadmap
- numpy
- pandas
- skit learn
- matplotlib
- seaborn

In [1]:
import numpy as np

#### creating array

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
#we can access element using index
arr = np.array([1,2,3,4,5,6,7,8])
arr[1] = 20
arr

array([ 1, 20,  3,  4,  5,  6,  7,  8])

In [11]:
np.arange(2,610)

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 18

In [12]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

###multidimensional array

In [13]:
# zeromatrix of size 3*5
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
# matrix of size 3*3 with random numbers and replace the numbers with 1,2,3  4,5,6  7,8,9 and then replace 2,5,8, with 20,50,80
matrix = np.array([[1,2,3],[3,4,5],[6,7,8]])
matrix[0, ] = [2,5,8]
matrix

array([[2, 5, 8],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
matrix[1,] = [20,50,80]
matrix

array([[ 2,  5,  8],
       [20, 50, 80],
       [ 6,  7,  8]])

In [21]:
matrix[2,] = [3,5,7]
matrix

array([[ 2,  5,  8],
       [20, 50, 80],
       [ 3,  5,  7]])

In [24]:
matrix


array([[ 2,  5,  8],
       [20, 50, 80],
       [ 3,  5,  7]])

### randomly generated array
- randn
- randint
- rand


In [31]:
#random numbers
number = np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

- use of seed
- dataset - shufle and split
- comparative analysis
- random forest, svm, LR

In [32]:
#randint
np.random.seed(2)
np.random.randint(low= 0, high = 100, size = (5,3))

array([[40, 15, 72],
       [22, 43, 82],
       [75,  7, 34],
       [49, 95, 75],
       [85, 47, 63]])

## linear algebra using numpy
- vector operation
- matrix multiplications
- vector vector
- matrix vector
- matrix- matriz
- identity matrix
- inverse matrix

In [33]:
u = np.array([2,4,5,6])


2*u

array([ 4,  8, 10, 12])

In [34]:
v = np.array([1,0,0,2])

u+v

array([3, 4, 5, 8])

In [35]:
u*v

array([ 2,  0,  0, 12])

In [36]:
v.shape[0]

4

In [ ]:
def multply(u, v):
  result = 0


### pandas
- dataframe
- series
- index
- access element
- filtering
- string operations
- handling missing values