<a href="https://colab.research.google.com/github/nishanN321/nishanN321/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Machine learning roadmap
- numpy
- pandas
- skit learn
- matplotlib
- seaborn

In [1]:
import numpy as np

#### creating array

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
#we can access element using index
arr = np.array([1,2,3,4,5,6,7,8])
arr[1] = 20
arr

array([ 1, 20,  3,  4,  5,  6,  7,  8])

In [7]:
np.arange(2,610)

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 18

In [8]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

###multidimensional array

In [9]:
# zeromatrix of size 3*5
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# matrix of size 3*3 with random numbers and replace the numbers with 1,2,3  4,5,6  7,8,9 and then replace 2,5,8, with 20,50,80
matrix = np.array([[1,2,3],[3,4,5],[6,7,8]])
matrix[0, ] = [2,5,8]
matrix

array([[2, 5, 8],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
matrix[1,] = [20,50,80]
matrix

array([[ 2,  5,  8],
       [20, 50, 80],
       [ 6,  7,  8]])

In [12]:
matrix[2,] = [3,5,7]
matrix

array([[ 2,  5,  8],
       [20, 50, 80],
       [ 3,  5,  7]])

In [13]:
matrix


array([[ 2,  5,  8],
       [20, 50, 80],
       [ 3,  5,  7]])

### randomly generated array
- randn
- randint
- rand


In [14]:
#random numbers
number = np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

- use of seed
- dataset - shufle and split
- comparative analysis
- random forest, svm, LR

In [15]:
#randint
np.random.seed(2)
np.random.randint(low= 0, high = 100, size = (5,3))

array([[40, 15, 72],
       [22, 43, 82],
       [75,  7, 34],
       [49, 95, 75],
       [85, 47, 63]])

## linear algebra using numpy
- vector operation
- matrix multiplications
- vector vector
- matrix vector
- matrix- matriz
- identity matrix
- inverse matrix

In [16]:
u = np.array([2,4,5,6])


2*u

array([ 4,  8, 10, 12])

In [17]:
v = np.array([1,0,0,2])

u+v

array([3, 4, 5, 8])

In [18]:
u*v

array([ 2,  0,  0, 12])

In [19]:
v.shape[0]

4

In [20]:
def multply(u, v):
  result = 0


### pandas
- dataframe
- series
- index
- access element
- filtering
- string operations
- handling missing values

### pandas
- to create series
- to assign the index in the series


In [21]:
import pandas as pd

### Series in pandas

In [22]:

my = pd.Series([1,2,3], index = ['a','b','c'])
my

a    1
b    2
c    3
dtype: int64

### DataFrame in pandas
- we can define data and column by ourself
- by dictionary

In [26]:
#columns = need to fill
data = [
    ["Nissan", "navara", 1992, 138, 4, "manual", "sub", 2000],
    ["hundai", "santro",2005, None, 2, "automatic", "small car", 1000],
    ["toyota", "hylux", 2010, 250, 6, "manual", "truck", 5000],
    ["BYD", "atto", 2020, None, None, "automatic", "sub", 2500],
    ["Nissan", "sunny", 2017, 260, 6, "manual", "sedan", 3000]
]

In [29]:
df = pd. DataFrame(data = data)
df

0       1     2      3    4          5          6     7
0  Nissan  navara  1992  138.0  4.0     manual        sub  2000
1  hundai  santro  2005    NaN  2.0  automatic  small car  1000
2  toyota   hylux  2010  250.0  6.0     manual      truck  5000
3     BYD    atto  2020    NaN  NaN  automatic        sub  2500
4  Nissan   sunny  2017  260.0  6.0     manual      sedan  3000

In [33]:
#using dictniory

data1  =[
    {
    "make" : "nissan",
    "model": "santro",
    "Year":2005,
    "engine Hp":138,
    "engine cylinder":4,
    "Transmission Type":"automatic",
    "vehichel":"small car",
    "MRP":1000
    },
    {
    "make" : "BYD",
    "model":"atto",
    "Year":2020,
    "engine Hp":150,
    "engine cylinder":6,
    "Transmission Type":"automatic",
    "vehichel":"suv",
    "MRP":2000
    }
]
df1 = pd.DataFrame(data = data1)
df1

make   model  Year  engine Hp  engine cylinder Transmission Type  \
0  nissan  santro  2005        138                4         automatic   
1     BYD    atto  2020        150                6         automatic   

    vehichel   MRP  
0  small car  1000  
1        suv  2000

In [36]:
df1[["engine Hp","Year"]]

engine Hp  Year
0        138  2005
1        150  2020

In [42]:
df["id"] = [10,20,30,40,50]
df

0       1     2      3    4          5          6     7  id
0  Nissan  navara  1992  138.0  4.0     manual        sub  2000  10
1  hundai  santro  2005    NaN  2.0  automatic  small car  1000  20
2  toyota   hylux  2010  250.0  6.0     manual      truck  5000  30
3     BYD    atto  2020    NaN  NaN  automatic        sub  2500  40
4  Nissan   sunny  2017  260.0  6.0     manual      sedan  3000  50

In [43]:
del df['id']
df

0       1     2      3    4          5          6     7
0  Nissan  navara  1992  138.0  4.0     manual        sub  2000
1  hundai  santro  2005    NaN  2.0  automatic  small car  1000
2  toyota   hylux  2010  250.0  6.0     manual      truck  5000
3     BYD    atto  2020    NaN  NaN  automatic        sub  2500
4  Nissan   sunny  2017  260.0  6.0     manual      sedan  3000

In [44]:
# index
df.index

RangeIndex(start=0, stop=5, step=1)

In [46]:
df.index = ['a', 'b', 'c', 'd', 'e']
df

0       1     2      3    4          5          6     7
a  Nissan  navara  1992  138.0  4.0     manual        sub  2000
b  hundai  santro  2005    NaN  2.0  automatic  small car  1000
c  toyota   hylux  2010  250.0  6.0     manual      truck  5000
d     BYD    atto  2020    NaN  NaN  automatic        sub  2500
e  Nissan   sunny  2017  260.0  6.0     manual      sedan  3000

In [53]:
# go to engine hp(3) to 150
df[3]['b'] = 150
df

/tmp/ipython-input-1929542583.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[3]['b'] = 150


0       1     2      3    4          5          6     7
a  Nissan  navara  1992  138.0  4.0     manual        sub  2000
b  hundai  santro  2005  150.0  2.0  automatic  small car  1000
c  toyota   hylux  2010  250.0  6.0     manual      truck  5000
d     BYD    atto  2020    NaN  NaN  automatic        sub  2500
e  Nissan   sunny  2017  260.0  6.0     manual      sedan  3000

In [54]:
df.iloc[[1,2,4]]

0       1     2      3    4          5          6     7
b  hundai  santro  2005  150.0  2.0  automatic  small car  1000
c  toyota   hylux  2010  250.0  6.0     manual      truck  5000
e  Nissan   sunny  2017  260.0  6.0     manual      sedan  3000

In [56]:
df = df.reset_index(drop = True)
df

0       1     2      3    4          5          6     7
0  Nissan  navara  1992  138.0  4.0     manual        sub  2000
1  hundai  santro  2005  150.0  2.0  automatic  small car  1000
2  toyota   hylux  2010  250.0  6.0     manual      truck  5000
3     BYD    atto  2020    NaN  NaN  automatic        sub  2500
4  Nissan   sunny  2017  260.0  6.0     manual      sedan  3000

In [57]:
df[3]*3

0    414.0
1    450.0
2    750.0
3      NaN
4    780.0
Name: 3, dtype: float64

In [58]:
df[2]>=2015

0    False
1    False
2    False
3     True
4     True
Name: 2, dtype: bool

In [64]:
#apply filter and return a dataframe only containing nissan
df[df[0] == 'Nissan'] #& (df[2] >=2015)

0       1     2      3    4       5      6     7
0  Nissan  navara  1992  138.0  4.0  manual    sub  2000
4  Nissan   sunny  2017  260.0  6.0  manual  sedan  3000

In [62]:
#nissan and make year greater than 2015
df2 = df[df[0] == 'Nissan']
df2[2]>=2015

0    False
4     True
Name: 2, dtype: bool

In [ ]:
#string operation


In [65]:
'machine learning is fun'.replace(' ', '_')

'machine_learning_is_fun'

In [69]:
'@rebant aryal, rebant_aryal'.replace("@",'')

'rebant aryal, rebant_aryal'

In [70]:
df1

make   model  Year  engine Hp  engine cylinder Transmission Type  \
0  nissan  santro  2005        138                4         automatic   
1     BYD    atto  2020        150                6         automatic   

    vehichel   MRP  
0  small car  1000  
1        suv  2000

In [80]:
df1['engine Hp'] = df1['engine Hp'].astype(str).str.replace(' ', '_').str.upper()
df1


make   model  Year engine Hp  engine cylinder Transmission Type  \
0  nissan  santro  2005       138                4         automatic   
1     BYD    atto  2020       150                6         automatic   

    vehichel   MRP  
0  small car  1000  
1        suv  2000

In [82]:
df.describe()

2           3         4            7
count     5.000000    4.000000  4.000000     5.000000
mean   2008.800000  199.500000  4.500000  2700.000000
std      11.077003   64.402381  1.914854  1483.239697
min    1992.000000  138.000000  2.000000  1000.000000
25%    2005.000000  147.000000  3.500000  2000.000000
50%    2010.000000  200.000000  5.000000  2500.000000
75%    2017.000000  252.500000  6.000000  3000.000000
max    2020.000000  260.000000  6.000000  5000.000000

In [83]:
df.nunique()

0    4
1    5
2    5
3    4
4    3
5    2
6    4
7    5
dtype: int64

In [85]:
#missing values
df.isnull().sum()

0    0
1    0
2    0
3    1
4    1
5    0
6    0
7    0
dtype: int64

'''SELECT column_name(s)
FROM table_name
WHERE condition
GROUP BY column_name(s)
ORDER BY column_name(s);'''

In [87]:
df.groupby(0).7.mean()

SyntaxError: invalid syntax (ipython-input-2123639485.py, line 1)

In [92]:
df1["engine Hp"].values


array(['138', '150'], dtype=object)

In [86]:
df

0       1     2      3    4          5          6     7
0  Nissan  navara  1992  138.0  4.0     manual        sub  2000
1  hundai  santro  2005  150.0  2.0  automatic  small car  1000
2  toyota   hylux  2010  250.0  6.0     manual      truck  5000
3     BYD    atto  2020    NaN  NaN  automatic        sub  2500
4  Nissan   sunny  2017  260.0  6.0     manual      sedan  3000

In [23]:
a = {
    "data" : [120,12,33],
    "science": [20,34,67],
    "matheamtics":[30,45,66]
}
series = pd.DataFrame(a, index = [0,4,5])
series

data  science  matheamtics
0   120       20           30
4    12       34           45
5    33       67           66

In [24]:
b = series["data"][5]
b

np.int64(33)

In [93]:
#save dataframe to csv file
df.to_csv("car_dataset")

In [95]:
#read dataset
df3 = pd.read_csv("car_dataset")
df3

Unnamed: 0       0       1     2      3    4          5          6     7
0           0  Nissan  navara  1992  138.0  4.0     manual        sub  2000
1           1  hundai  santro  2005  150.0  2.0  automatic  small car  1000
2           2  toyota   hylux  2010  250.0  6.0     manual      truck  5000
3           3     BYD    atto  2020    NaN  NaN  automatic        sub  2500
4           4  Nissan   sunny  2017  260.0  6.0     manual      sedan  3000

In [109]:
df3.columns

Index(['Unnamed: 0', '0', '1', '2', '3', '4', '5', '6', '7'], dtype='object')

In [114]:
#delete column unnamed
del df3['Unnamed: 0']


KeyError: 'Unnamed: 0'

In [115]:
df3

0       1     2      3    4          5          6     7
0  Nissan  navara  1992  138.0  4.0     manual        sub  2000
1  hundai  santro  2005  150.0  2.0  automatic  small car  1000
2  toyota   hylux  2010  250.0  6.0     manual      truck  5000
3     BYD    atto  2020    NaN  NaN  automatic        sub  2500
4  Nissan   sunny  2017  260.0  6.0     manual      sedan  3000